export default function Work(){
    return(
        <div className="flex flex-col w-9/12 self-center mob:w-11/12 pt-8 mob:pt-3">
            <section className="flex font-semibold p-6 text-2xl mt-6 rounded-lg bg-[#202020] justify-center w-10/12 self-center mob:w-auto mob:text-xl">
                <p className=" "><span className="text-[#943636] font-bold">VALOTAG</span><br/><br/>VALOTAG IS MY ATTEMPT TO TRY AND MAKE A DIFFERENCE IN THE INDIAN VALORANT COMMUNITY WHERE THERE IS LACK OF EMPHASIS ON THE T2 SIDE OF THE THINGS. <br/><br/>VALOTAG IS A PRODUCT TO CENTRALIZE THE T2 SCENE WHICH CAN POTENTIALLY JOURNAL THE JOURNEY OF EVERY T2 PLAYERS WHO MAKES IT BIG, WHILE PROVIDING THE PLAYERS WITH SCOUTING OPPORTUNITIES AND THE SCOUTS A PLATFORM TO KEEP, COLLECT AND MONITOR ALL THE PLAYERS THEY FEEL DESERVE A CHANCE.<br/><br/> THE PRODUCT HAS BEEN SUBMITTED TO <span className="text-[#943636]">RIOT GAMES</span> TO DECIDE WEATHER IT DESERVES A FAIR SHOT TO UTILIZE THE RIOT API.
                </p>
            </section>
            <section className="flex font-semibold p-6 text-2xl my-6 rounded-lg bg-[#202020] justify-center w-10/12 self-center mob:w-auto mob:text-xl">
                <p className=""><span className="text-[#943636] font-bold">REACTION TIMER</span><br/><br/>MADE A BECNHMARK REACTION TIMER AS A WARMUP BEFORE I START WORKING ON VALOTAG, ALSO WITH AN INTENTION TO LATER PLUG THE SAME INTO VALOTAG FOR NOT ONLY THE PRO PLAYERS TO UTILIZE IT TO THEIR LEVEL BEST BUT ALSO FOR ME TO COLLECT THE DATA AND ANALYSE THE SAME TO MAKE SOME DEDUCTIONS.<br/><br/> REACTION TIMER WAS BUILT USING VANILLA JAVASCRIPT WITH AN INTENTION TO MIMIC REACT-LIKE SINGLE PAGE FUNCTIONALITY. <br/><br/>THE WEB-APP ALSO HAD THE ABILITY TO CACHE THE ENTIRE DATA OF ALL THE PEOPLE WHO TAKE THE TEST ON THE PARTICULAR DEVICE AND DISPLAY NOT ONLY THE MINIMUM BUT ALSO THE AVERAGE REACTION TIME OF EVERY INDIVIDUAL IN A LAEADERBOARD MANNER.
                </p>
            </section>
        </div>
    );
}